import { motion, AnimatePresence } from "framer-motion";
import { Copy, Download, Image as ImageIcon, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { HistoryEntry } from "@/types/caption.types";
import { toast } from "sonner";

interface Props {
  entry: HistoryEntry | null;
  isLoading: boolean;
}

function downloadText(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

async function downloadCard(imageUrl: string, caption: string) {
  const img = new Image();
  img.crossOrigin = "anonymous";
  img.src = imageUrl;
  await new Promise((r) => (img.onload = r));
  const W = 1200;
  const H = Math.round((img.height / img.width) * W) + 220;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "#0f1014";
  ctx.fillRect(0, 0, W, H);
  ctx.drawImage(img, 0, 0, W, H - 220);
  ctx.fillStyle = "#e5e7eb";
  ctx.font = "500 28px ui-sans-serif, Inter";
  // wrap
  const words = caption.split(" ");
  let line = "";
  let y = H - 160;
  const maxW = W - 80;
  for (const w of words) {
    const test = line ? line + " " + w : w;
    if (ctx.measureText(test).width > maxW) {
      ctx.fillText(line, 40, y);
      y += 38;
      line = w;
    } else line = test;
  }
  if (line) ctx.fillText(line, 40, y);
  ctx.fillStyle = "#a78bfa";
  ctx.font = "500 14px ui-monospace, Menlo";
  ctx.fillText("generated by Caption.ai", 40, H - 30);
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "caption-card.png";
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}

export function CaptionOutput({ entry, isLoading }: Props) {
  return (
    <div className="rounded-lg border border-border bg-card">
      <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
        <div className="flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          <span className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
            generated caption
          </span>
        </div>
        {entry && !isLoading && (
          <Badge variant="secondary" className="font-mono text-[10px]">
            confidence {(entry.confidence * 100).toFixed(1)}%
          </Badge>
        )}
      </div>

      <div className="min-h-[140px] px-5 py-6">
        <AnimatePresence mode="wait">
          {isLoading ? (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-2"
            >
              <div className="flex items-center gap-2 font-mono text-xs text-muted-foreground">
                <motion.span
                  animate={{ opacity: [0.3, 1, 0.3] }}
                  transition={{ duration: 1.2, repeat: Infinity }}
                  className="inline-block h-1.5 w-1.5 rounded-full bg-primary"
                />
                running inference…
              </div>
              {[0, 1, 2].map((i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0.2 }}
                  animate={{ opacity: [0.2, 0.5, 0.2] }}
                  transition={{ duration: 1.4, repeat: Infinity, delay: i * 0.15 }}
                  className="h-3 rounded bg-muted"
                  style={{ width: `${90 - i * 18}%` }}
                />
              ))}
            </motion.div>
          ) : entry ? (
            <motion.p
              key={entry.id}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
              className="font-mono text-base leading-relaxed text-foreground"
            >
              <span className="text-primary">› </span>
              {entry.caption}
            </motion.p>
          ) : (
            <p className="font-mono text-sm text-muted-foreground">
              {"// upload an image to generate a caption"}
            </p>
          )}
        </AnimatePresence>
      </div>

      {entry && !isLoading && (
        <div className="flex flex-wrap gap-2 border-t border-border bg-background/40 px-4 py-2.5">
          <Button
            size="sm"
            variant="ghost"
            className="h-7 gap-1.5 font-mono text-xs"
            onClick={() => {
              navigator.clipboard.writeText(entry.caption);
              toast.success("Copied to clipboard");
            }}
          >
            <Copy className="h-3 w-3" /> copy
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 gap-1.5 font-mono text-xs"
            onClick={() => downloadText("caption.txt", entry.caption)}
          >
            <Download className="h-3 w-3" /> .txt
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 gap-1.5 font-mono text-xs"
            onClick={() => downloadCard(entry.imageUrl, entry.caption)}
          >
            <ImageIcon className="h-3 w-3" /> .png card
          </Button>
        </div>
      )}
    </div>
  );
}
